# Generated by Django 3.0.6 on 2020-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoles',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
