# Generated by Django 3.0.6 on 2020-05-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0002_consoles_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoles',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
