# Generated by Django 3.0.6 on 2020-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200507_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
