# Generated by Django 3.0.6 on 2020-05-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_games_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
