# Generated by Django 3.0.6 on 2020-05-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_games_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
