# Generated by Django 3.0.6 on 2020-05-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200508_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='emulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emulator', models.CharField(max_length=1000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
            ],
        ),
    ]
