# Generated by Django 3.0.6 on 2020-05-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consoles', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('user_name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('street_name', models.CharField(blank=True, max_length=225)),
                ('house_nr', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=225)),
                ('country', models.CharField(blank=True, max_length=225)),
                ('postal_code', models.FloatField()),
                ('password', models.CharField(max_length=225)),
                ('role', models.CharField(blank=True, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField()),
                ('amount', models.FloatField()),
                ('order_nr', models.FloatField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Accounts')),
                ('console_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles')),
                ('game_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.Accounts')),
                ('console_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles')),
                ('game_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
            ],
        ),
        migrations.CreateModel(
            name='AccountImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Accounts')),
            ],
        ),
    ]
