# Generated by Django 3.0.6 on 2020-05-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='house_nr',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='postal_code',
            field=models.FloatField(blank=True),
        ),
    ]
