# Generated by Django 3.0.6 on 2020-05-13 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200508_1204'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consoles', '0004_auto_20200508_1204'),
        ('account', '0002_auto_20200508_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles')),
                ('game_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(blank=True, max_length=225)),
                ('house_nr', models.FloatField(blank=True)),
                ('city', models.CharField(blank=True, max_length=225)),
                ('country', models.CharField(blank=True, max_length=225)),
                ('postal_code', models.FloatField(blank=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField()),
                ('amount', models.FloatField()),
                ('order_nr', models.FloatField()),
                ('console_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles')),
                ('game_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='console_id',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='console_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='game_id',
        ),
        migrations.DeleteModel(
            name='AccountImage',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
