# Generated by Django 3.0.6 on 2020-05-14 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200508_1204'),
        ('consoles', '0004_auto_20200508_1204'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20200513_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles')),
                ('game_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
