# Generated by Django 3.0.6 on 2020-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_searchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='console_id',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='game_id',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
