# Generated by Django 3.0.6 on 2020-05-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200514_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.FloatField(default=0),
        ),
    ]
