# Generated by Django 3.0.6 on 2020-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200514_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='console_id',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='game_id',
            field=models.FloatField(),
        ),
    ]
