# Generated by Django 3.0.6 on 2020-05-15 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200508_1204'),
        ('consoles', '0004_auto_20200508_1204'),
        ('account', '0009_auto_20200514_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='console_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_nr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('console_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles')),
                ('game_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Order')),
            ],
        ),
    ]
