# Generated by Django 3.0.6 on 2020-05-15 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0004_auto_20200508_1204'),
        ('games', '0005_auto_20200508_1204'),
        ('account', '0010_auto_20200515_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='console_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consoles.Consoles'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='game_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Games'),
        ),
    ]
