# Generated by Django 3.0.6 on 2020-05-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200515_0110'),
        ('account', '0010_auto_20200515_0453'),
    ]

    operations = [
    ]
