# Generated by Django 3.0.6 on 2020-05-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_merge_20200515_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=225)),
                ('card_num', models.IntegerField()),
                ('Exp_date', models.DateField()),
                ('CVC', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='location',
            name='house_nr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_name',
            field=models.CharField(max_length=225),
        ),
    ]
